apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: basket-service
build:
  artifacts:
    - image: pcpartsshop/basket-service
      docker:
        dockerfile: Dockerfile
  local: {}
manifests:
  rawYaml:
    - k8s/*
