apiVersion: v1
kind: Service
metadata:
  name: basket-service
spec:
  selector:
    app: basket-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003
  type: NodePort
